services:
  web:
    build: .
    command: bash -lc "/app/.venv/bin/gunicorn 'backend.app:create_app()' -b 0.0.0.0:5000 -w 4"
    environment:
      - DATABASE_URL=postgresql+psycopg2://news:news@db:5432/news
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "5080:5000"
    depends_on: [db, redis]
  worker:
    build: .
    command: bash -lc "/app/.venv/bin/celery -A tasks.app.celery_app worker --loglevel=INFO"
    environment:
      - DATABASE_URL=postgresql+psycopg2://news:news@db:5432/news
      - REDIS_URL=redis://redis:6379/0
      - BACKEND_URL=http://web:5000
    depends_on: [db, redis]
  beat:
    build: .
    command: bash -lc "/app/.venv/bin/celery -A tasks.app.celery_app beat --loglevel=INFO"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - BACKEND_URL=http://web:5000
    depends_on: [worker]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=news
      - POSTGRES_PASSWORD=news
      - POSTGRES_DB=news
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
volumes:
  dbdata: {}
